spring:
  datasource:
    url: jdbc:mysql://localhost:3307/hax?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: yjgbg
    password: 1314
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: true # 如果为false：则在transactional结束的时候会关闭connection，如果为true，则在请求返回的时候关闭connection
    generate-ddl: true